---
universes:
  - name: Direct
    id: 0
  - name: DS-1-12
    id: 1
    ipaddr: 172.1.1.64
    artnet_u: 0
  - name: DS-1-34
    id: 2
    ipaddr: 172.1.1.64
    artnet_u: 1
  - name: DS-1-56
    id: 3
    ipaddr: 172.1.1.64
    artnet_u: 2
  - name: DS-1-78
    id: 4
    ipaddr: 172.1.1.64
    artnet_u: 3

  - name: DS-2-12
    id: 5
    ipaddr: 172.1.1.65
    artnet_u: 0
  - name: DS-2-34
    id: 6
    ipaddr: 172.1.1.65
    artnet_u: 1
  - name: DS-2-56
    id: 7
    ipaddr: 172.1.1.65
    artnet_u: 2
  - name: DS-2-78
    id: 8
    ipaddr: 172.1.1.65
    artnet_u: 3

  - name: DS-3-12
    id: 9
    ipaddr: 172.1.1.66
    artnet_u: 0
  - name: DS-3-34
    id: 10
    ipaddr: 172.1.1.66
    artnet_u: 1
  - name: DS-3-56
    id: 11
    ipaddr: 172.1.1.66
    artnet_u: 2
  - name: DS-3-78
    id: 12
    ipaddr: 172.1.1.66
    artnet_u: 3
    
  - name: DS-4-12
    id: 13
    ipaddr: 172.1.1.67
    artnet_u: 0
  - name: DS-4-34
    id: 14
    ipaddr: 172.1.1.67
    artnet_u: 1
  - name: DS-4-56
    id: 15
    ipaddr: 172.1.1.67
    artnet_u: 2
  - name: DS-4-78
    id: 16
    ipaddr: 172.1.1.67
    artnet_u: 3

fixtures: 
  - name: ds-1-1
    model: Step Row 64 Heads
    u: 1
    a: 0
  - name: ds-1-2
    model: Step Row 64 Heads
    u: 1
    a: 192
  - name: ds-1-3
    model: Step Row 64 Heads
    u: 2
    a: 0
  - name: ds-1-4
    model: Step Row 64 Heads
    u: 2
    a: 192
  - name: ds-1-5
    model: Step Row 64 Heads
    u: 3
    a: 0
  - name: ds-1-6
    model: Step Row 64 Heads
    u: 3
    a: 192
  - name: ds-1-7
    model: Step Row 64 Heads
    u: 4
    a: 0
  - name: ds-1-8
    model: Step Row 64 Heads
    u: 4
    a: 192

  - name: ds-2-1
    model: Step Row 64 Heads
    u: 5
    a: 0
  - name: ds-2-2
    model: Step Row 64 Heads
    u: 5
    a: 192
  - name: ds-2-3
    model: Step Row 64 Heads
    u: 6
    a: 0
  - name: ds-2-4
    model: Step Row 64 Heads
    u: 6
    a: 192
  - name: ds-2-5
    model: Step Row 64 Heads
    u: 7
    a: 0
  - name: ds-2-6
    model: Step Row 64 Heads
    u: 7
    a: 192
  - name: ds-2-7
    model: Step Row 64 Heads
    u: 8
    a: 0
  - name: ds-2-8
    model: Step Row 64 Heads
    u: 8
    a: 192

  - name: ds-3-1
    model: Step Row 64 Heads
    u: 9
    a: 0
  - name: ds-3-2
    model: Step Row 64 Heads
    u: 9
    a: 192
  - name: ds-3-3
    model: Step Row 64 Heads
    u: 10
    a: 0
  - name: ds-3-4
    model: Step Row 64 Heads
    u: 10
    a: 192
  - name: ds-3-5
    model: Step Row 64 Heads
    u: 11
    a: 0
  - name: ds-3-6
    model: Step Row 64 Heads
    u: 11
    a: 192
  - name: ds-3-7
    model: Step Row 64 Heads
    u: 12
    a: 0
  - name: ds-3-8
    model: Step Row 64 Heads
    u: 12
    a: 192

  - name: ds-4-1
    model: Step Row 64 Heads
    u: 13
    a: 0
  - name: ds-4-2
    model: Step Row 64 Heads
    u: 13
    a: 192
  - name: ds-4-3
    model: Step Row 64 Heads
    u: 14
    a: 0
  - name: ds-4-4
    model: Step Row 64 Heads
    u: 14
    a: 192
  - name: ds-4-5
    model: Step Row 64 Heads
    u: 15
    a: 0
  - name: ds-4-6
    model: Step Row 64 Heads
    u: 15
    a: 192
  - name: ds-4-7
    model: Step Row 64 Heads
    u: 16
    a: 0
  - name: ds-4-8
    model: Step Row 64 Heads
    u: 16
    a: 192

fixture_groups:
  - type: step
    name: ds-1
    rows: 8
    cols: 64
    fixtures:
      - name: ds-1-1
      - name: ds-1-2
      - name: ds-1-3
      - name: ds-1-4
      - name: ds-1-5
      - name: ds-1-6
      - name: ds-1-7
      - name: ds-1-8

#   # - type: step
#   #   name: us-2
#   #   rows: 8
#   #   cols: 64
#   #   fixtures: step_row
#   #  # ip_address: 172.18.1.202

#   # - type: step
#   #   name: us-3
#   #   rows: 8
#   #   cols: 64
#   #   fixtures: step_row
#   #  #  ip_address: 172.18.1.203
    
#   # - type: step
#   #   name: us-4
#   #   rows: 8
#   #   cols: 64
#   #   fixtures: step_row
#   #   ip_address: 172.18.1.204

#   # - name: us
#   #   type: matrix
#   #   rows: 8
#   #   cols: 256
#   #   fixtures:
#   #     - us-1
#   #     - us-2
#   #     - us-3
#   #     - us-4 
    




